export enum ENV {
  DATABASE_URL = 'DATABASE_URL',
  TURSO_AUTH_TOKEN = 'TURSO_AUTH_TOKEN',

  JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
  JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DEVELOPMENT_URL = 'DEVELOPMENT_URL',
  PRODUCTION_URL = 'PRODUCTION_URL',

  ROOT_API_KEY = 'ROOT_API_KEY',
  APP_NAME = 'APP_NAME',
  LOG_LEVEL = 'LOG_LEVEL',
  BREVO_API_KEY = 'BREVO_API_KEY',
  BREVO_SENDER_EMAIL = 'BREVO_SENDER_EMAIL',
  COMPANY_NAME = 'COMPANY_NAME',

  FRONTEND_URL = 'FRONTEND_URL',
  // Google OAuth Configuration
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_REDIRECT_URI = 'GOOGLE_REDIRECT_URI',

  // Storage Configuration
  STORAGE_PROVIDER = 'STORAGE_PROVIDER',
  MAX_FILE_SIZE = 'MAX_FILE_SIZE',
  AWS_REGION = 'AWS_REGION',
  S3_PUBLIC_BUCKET_NAME = 'S3_PUBLIC_BUCKET_NAME',
  S3_PRIVATE_BUCKET_NAME = 'S3_PRIVATE_BUCKET_NAME',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
}
