export enum ENV {
  DATABASE_URL = 'DATABASE_URL',
  TURSO_AUTH_TOKEN = 'TURSO_AUTH_TOKEN',

  JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
  JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DEVELOPMENT_URL = 'DEVELOPMENT_URL',
  PRODUCTION_URL = 'PRODUCTION_URL',

  APP_NAME = 'APP_NAME',
  LOG_LEVEL = 'LOG_LEVEL',
}
