export enum EmailType {
  // Welcome emails for different user types
  WELCOME_ADMIN = 'WELCOME_ADMIN',
  WELCOME_USER = 'WELCOME_USER',

  // Authentication related emails
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  LOGIN_REMINDER = 'LOGIN_REMINDER',
  ACCOUNT_ACTIVATION = 'ACCOUNT_ACTIVATION',

  // Wellness and engagement emails
  WELLNESS_TIP = 'WELLNESS_TIP',
  WEEKLY_INSPIRATION = 'WEEKLY_INSPIRATION',
  PROGRAMME_REMINDER = 'PROGRAMME_REMINDER',
  WEBINAR_INVITATION = 'WEBINAR_INVITATION',

  // Business and corporate emails
  CORPORATE_WELCOME = 'CORPORATE_WELCOME',
  WORKSHOP_CONFIRMATION = 'WORKSHOP_CONFIRMATION',
  POLICY_TOOLKIT_ACCESS = 'POLICY_TOOLKIT_ACCESS',

  // Newsletter and marketing emails
  NEWSLETTER_SUBSCRIPTION = 'NEWSLETTER_SUBSCRIPTION',
  PRODUCT_LAUNCH = 'PRODUCT_LAUNCH',
  SPECIAL_OFFER = 'SPECIAL_OFFER',

  // Account management emails
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  ACCOUNT_DEACTIVATION = 'ACCOUNT_DEACTIVATION',
  SUBSCRIPTION_RENEWAL = 'SUBSCRIPTION_RENEWAL',
}
