export enum EmailType {
  // Welcome emails for different user types
  WELCOME_ADMIN = 'WELCOME_ADMIN',
  WELCOME_USER = 'WELCOME_USER',

  // Authentication related emails
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS',
  LOGIN_REMINDER = 'LOGIN_REMINDER',
  ACCOUNT_ACTIVATION = 'ACCOUNT_ACTIVATION',

  ACCOUNT_DEACTIVATION = 'ACCOUNT_DEACTIVATION',

  // Newsletter and marketing emails
  NEWSLETTER_SUBSCRIPTION = 'NEWSLETTER_SUBSCRIPTION',

  SUBSCRIPTION_RENEWAL = 'SUBSCRIPTION_RENEWAL',
}
